print("loading..")
input()
print("loading..")
input()
print("loading..")
input()
name = input("welcome...what's your name! ") 
print(f"{name}..that's a cool name!")
input()
print("i will tell you a little story! but it comes at a cost...")
input()
print("i need your help.")
input()
day = input("name a day of the week! ") 
adjective = input("okay! name an adjective! ") 
place = input("now name a place. ") 
person = input("almost finished! name a family member or friend! ")
emotion = input("last one! name an emotion. ") 
print("okay cute!")
print(f"on {day}, i go on a {adjective} trip to {place} with my {person}.")
print ("i am very {emotion}" for this trip.)