name = input("welcome...what's your name! ") 
print(f"{name}..that's a cool name!")
input()
print("i will tell you a little story! but it comes at a cost...")
input()
print("i need your help.")
input()
day = input("name a day of the week! ") 
adjective = input("okay! name an adjective! ") 
place = input("now name a place. ") 
person = input("almost finished! name a family member or friend! ")
emotion = input("last one! name an emotion. ") 
print("okay cute!")
input()
print(f"on {day}, i go on a {adjective} trip to {place} with my {person}.")
input()
print (f"i am very {emotion} for this trip.")
input()
print("that was beautiful!")
print("now here's an extra small story!")
input()
animal = input("name an animal!")
title = input("type a name!")
verb = input("name a past tense verb! ")
store = input("name a store... ")
item = input("now name an item! ")
movie = input("name a movie!")
print("ready to hear your story!?")
input()
print(f"once, there was a {animal} named {title}.")
print(f"he {verb} to the {store}. then he bought a {item}!")
print("he went home and watched {movie}!")