print("Welcome...")
print("\n\n")
name = input("Type your name and press enter! ")    
print(f"hi {name}!")
print("\n\n") 
input()                                 
print("figure out my two truths and a lie...")
input()
print("I was born in Burlington, Vermont!")  
input()              
print("I own 20 vinyls/records!")
input()
print("I earned a bachelor's degree at Stanford University.")
input()
print("If you guessed the third, you would be...")
input()
input()
input()
print("WRONG!")
print("i own 22 vinyls...")