print("Welcome...")
print("\n\n")
name = input("Type your name and press enter! ")    
print(
print("\n\n") 
input()                                 
print("figure out my two truths and a lie...")
print("\n\n")
input()
print("I was born in Burlington, Vermont!")  
print("\n\n")  
input()                       
print("I own over 20 vinyls/records!")
print("\n\n")
input()
print("I earned a bachelor's degree at Stanford University.")